# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'Hackathon-Googlee' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hackathon-Googlee
	 pod 'GoogleMaps'
	  pod 'GooglePlaces'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'Google/SignIn'
end
